/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SupplyChainAbi } from "./SupplyChainAbi";

export { SupplyChainAbi__factory } from "./factories/SupplyChainAbi__factory";
